# Generated by Django 2.1.4 on 2019-01-14 02:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 2, 10, 44, 811464, tzinfo=utc)),
        ),
    ]
