# Generated by Django 2.1.4 on 2019-01-14 02:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190114_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 2, 27, 20, 739103, tzinfo=utc), max_length=10),
        ),
    ]
