# Generated by Django 2.1.4 on 2019-01-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190114_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pub_date',
            field=models.DateTimeField(verbose_name=' date published'),
        ),
    ]
